# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Web_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 495)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 0, 271, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.quesiton = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.quesiton.setObjectName("quesiton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.quesiton)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(570, 0, 113, 32))
        self.pushButton.setObjectName("查询")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(300, 0, 52, 20))
        self.label_2.setObjectName("label_2")
        self.level = QtWidgets.QComboBox(Form)
        self.level.setGeometry(QtCore.QRect(360, 0, 104, 26))
        self.level.setObjectName("level")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.level.addItem("")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(60, 70, 651, 201))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(60, 310, 641, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(360, 50, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(360, 290, 60, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "搜索内容"))
        self.pushButton.setText(_translate("Form", "查询"))
        self.label_2.setText(_translate("Form", "用户等级"))
        self.level.setItemText(0, _translate("Form", "董事长"))
        self.level.setItemText(1, _translate("Form", "总经理"))
        self.level.setItemText(2, _translate("Form", "部门经理"))
        self.level.setItemText(3, _translate("Form", "员工"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(6)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(7)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(8)
        item.setText(_translate("Form", ""))
        item = self.listWidget.item(9)
        item.setText(_translate("Form", ""))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Form", "目录"))
        self.label_4.setText(_translate("Form", "内容"))

